// <auto-generated />
using System;
using APBDPROJEKT.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APBDPROJEKT.Migrations
{
    [DbContext(typeof(RevenueDbContext))]
    partial class RevenueDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APBDPROJEKT.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Login = "appUser1",
                            Password = "password1",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Login = "appUser2",
                            Password = "password2",
                            Role = "User"
                        });
                });

            modelBuilder.Entity("APBDPROJEKT.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("APBDPROJEKT.Entities.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BonusSupportYears")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSigned")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SoftwareId")
                        .HasColumnType("int");

                    b.Property<string>("SoftwareVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("SoftwareId");

                    b.ToTable("Contracts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BonusSupportYears = 0,
                            ClientId = 1,
                            EndDate = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSigned = true,
                            Price = 4500.00m,
                            SoftwareId = 1,
                            SoftwareVersion = "1.0.0",
                            StartDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            BonusSupportYears = 1,
                            ClientId = 3,
                            EndDate = new DateTime(2026, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsSigned = false,
                            Price = 3000.00m,
                            SoftwareId = 2,
                            SoftwareVersion = "2.0.0",
                            StartDate = new DateTime(2026, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("APBDPROJEKT.Entities.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoftwareId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(4,2)");

                    b.HasKey("Id");

                    b.HasIndex("SoftwareId");

                    b.ToTable("Discounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndDate = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Discount 1",
                            SoftwareId = 1,
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 10.00m
                        },
                        new
                        {
                            Id = 2,
                            EndDate = new DateTime(2026, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Discount 2",
                            SoftwareId = 2,
                            StartDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 20.00m
                        });
                });

            modelBuilder.Entity("APBDPROJEKT.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 2000.00m,
                            ContractId = 1,
                            Date = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Amount = 2500.00m,
                            ContractId = 1,
                            Date = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("APBDPROJEKT.Entities.Software", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePricePerYear")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Software");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePricePerYear = 2500.00m,
                            Category = "Education",
                            Description = "Software Description 1",
                            Name = "Software 1",
                            Version = "1.0.0"
                        },
                        new
                        {
                            Id = 2,
                            BasePricePerYear = 5000.00m,
                            Category = "Finance",
                            Description = "Software Description 2",
                            Name = "Software 2",
                            Version = "2.0.0"
                        });
                });

            modelBuilder.Entity("APBDPROJEKT.Entities.CompanyClient", b =>
                {
                    b.HasBaseType("APBDPROJEKT.Entities.Client");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Krs")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasIndex("Krs")
                        .IsUnique()
                        .HasFilter("[Krs] IS NOT NULL");

                    b.ToTable("CompanyClients");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Address = "ul. Trzecia 3, 00-001 Warszawa",
                            Email = "third.user@poczta.com",
                            PhoneNumber = "123654789",
                            CompanyName = "CorporationFirst",
                            Krs = "0000123456"
                        },
                        new
                        {
                            Id = 4,
                            Address = "ul. Czwarta 4, 30-000 Kraków",
                            Email = "fourth.user@poczta.com",
                            PhoneNumber = "321456987",
                            CompanyName = "CorporationSecond",
                            Krs = "0000234567"
                        });
                });

            modelBuilder.Entity("APBDPROJEKT.Entities.IndividualClient", b =>
                {
                    b.HasBaseType("APBDPROJEKT.Entities.Client");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pesel")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasIndex("Pesel")
                        .IsUnique()
                        .HasFilter("[Pesel] IS NOT NULL");

                    b.ToTable("IndividualClients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "ul. Pierwsza 1, 00-001 Warszawa",
                            Email = "first.user@poczta.com",
                            PhoneNumber = "123456789",
                            FirstName = "John",
                            IsDeleted = false,
                            LastName = "Doe",
                            Pesel = "12345678901"
                        },
                        new
                        {
                            Id = 2,
                            Address = "ul. Druga 2, 30-000 Kraków",
                            Email = "second.user@poczta.com",
                            PhoneNumber = "987654321",
                            FirstName = "Adam",
                            IsDeleted = false,
                            LastName = "Smith",
                            Pesel = "23456789012"
                        });
                });

            modelBuilder.Entity("APBDPROJEKT.Entities.Contract", b =>
                {
                    b.HasOne("APBDPROJEKT.Entities.Client", "Client")
                        .WithMany("Contracts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APBDPROJEKT.Entities.Software", "Software")
                        .WithMany()
                        .HasForeignKey("SoftwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Software");
                });

            modelBuilder.Entity("APBDPROJEKT.Entities.Discount", b =>
                {
                    b.HasOne("APBDPROJEKT.Entities.Software", "Software")
                        .WithMany("Discounts")
                        .HasForeignKey("SoftwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Software");
                });

            modelBuilder.Entity("APBDPROJEKT.Entities.Payment", b =>
                {
                    b.HasOne("APBDPROJEKT.Entities.Contract", "Contract")
                        .WithMany("Payments")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("APBDPROJEKT.Entities.CompanyClient", b =>
                {
                    b.HasOne("APBDPROJEKT.Entities.Client", null)
                        .WithOne()
                        .HasForeignKey("APBDPROJEKT.Entities.CompanyClient", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("APBDPROJEKT.Entities.IndividualClient", b =>
                {
                    b.HasOne("APBDPROJEKT.Entities.Client", null)
                        .WithOne()
                        .HasForeignKey("APBDPROJEKT.Entities.IndividualClient", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("APBDPROJEKT.Entities.Client", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("APBDPROJEKT.Entities.Contract", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("APBDPROJEKT.Entities.Software", b =>
                {
                    b.Navigation("Discounts");
                });
#pragma warning restore 612, 618
        }
    }
}
